server:
  port: 8082
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HUB-MOD/config-data.git
          default-label: main
          searchPaths: /ConfigData
  application:
    name: config-server